apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosxih-python-app
  annotations:
    deployed-at: "Sun Feb 22 03:25:15 UTC 2026"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nosxih-app
  template:
    metadata:
      labels:
        app: nosxih-app
    spec:
      containers:
      - name: python-app
        image: ghcr.io/hixson/nosxih-python-app:593c948202d43a16aae1df08a5ce003cda4d5ec4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 # Corrected indentation: aligned under image
        volumeMounts:
        - name: qnap-volume
          mountPath: /app/data # Python app looks for files here
      volumes:
      - name: qnap-volume
        persistentVolumeClaim:
          claimName: qnap-nfs-pvc
