apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosxih-python-app
  annotations:
    deployed-at: "Sun Feb 22 03:25:15 UTC 2026"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nosxih-app
  template:
    metadata:
      labels:
        app: nosxih-app
    spec:
      containers:
      - name: python-app
        image: ghcr.io/hixson/nosxih-python-app:4be646191a37833da1a440a9c033404f1ed231c0
        env:
        - name: APP_VERSION
          value: "4be646191a37833da1a440a9c033404f1ed231c0"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: qnap-volume
          mountPath: /app/data # Python app looks for files here
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: qnap-volume
        persistentVolumeClaim:
          claimName: qnap-nfs-pvc
